/* Generated by Doubao AI agent
*/


import { JSX } from "react";
import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useBaseUrl from '@docusaurus/useBaseUrl';

const MenuItems = [
  {
    title: 'Graphics API',
    link: '/docs/RenderWorks/GraphicsAPI/mvp',
    // 你只需要在这里填你的图片列表，支持 bg1~10
    images: ['/img/bg1.jpg', '/img/bg2.jpg', '/img/bg3.jpg']
  },
  {
    title: 'Render Algorithm',
    link: '/docs/RenderWorks/GraphicsAPI/shadingpipeline',
    images: ['/img/bg4.jpg', '/img/bg5.jpg', '/img/bg6.jpg']
  },
  {
    title: 'Debian Docs',
    link: '/docs/DebianTesting/dkms',
    images: ['/img/bg7.jpg', '/img/bg8.jpg']
  },
  {
    title: 'Game Demo',
    link: '/blog',
    images: ['/img/bg9.jpg', '/img/bg10.jpg']
  },
];

export default function Home(): JSX.Element {
  return (
    <Layout noFooter title="Home" description="COD Style Menu">
      <div className="cod-container">
        {MenuItems.map((item, idx) => (
          <Link key={idx} to={item.link} className="cod-item">
            
            {/* 多图淡入淡出层 */}
            <div className="cod-slider">
              {item.images.map((img, imgIdx) => (
                <div
                  key={imgIdx}
                  className="cod-slide"
                  style={{ backgroundImage: `url(${useBaseUrl(img)})` }}
                />
              ))}
            </div>

            <div className="cod-title">{item.title}</div>
          </Link>
        ))}
      </div>
    </Layout>
  );
}